### ISSUE TITLE
cross prdocut use fix

### ISSUE THREAD

**Issue by mzhouURI** [uri-ocean-robotics/mvp_control#7]
https://github.com/uri-ocean-robotics/mvp_control/blob/769db8ea00f765123e864fa99aa008f2ee86a140/src/mvp_control/mvp_control_ros.cpp#L464

**Comment by linzha0** [comment]
fixed in [this commits](https://github.com/uri-ocean-robotics/mvp_control/commit/2d56c73e181b4c490ed2206b7f049210340b88c8), tested in alpha_img setup, however, this should be verified in RACE vehicle for all the degree of freedom test.

**Comment by linzha0** [comment]
close for now
